# 项目相关配置
im:
  # 名称
  name: Qtech-Im
  # 版本
  version: 3.8.8
  # 版权年份
  copyrightYear: 2024
  # 文件路径 示例（ Windows配置D:/qtech/uploadPath，Linux配置 /home/qtech/uploadPath）
  profile: /home/qtech/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8079
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.qtech: debug
    org.springframework: warn
    com.github.pagehelper: warn

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: prod
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 200MB
      # 设置总上传的文件大小
      max-request-size: 200MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true

  kafka:
    bootstrap-servers:
      - 10.170.6.170:9092
      - 10.170.6.171:9092
      - 10.170.6.172:9092
    consumer:
      group-id: device-status-group
      auto-offset-reset: latest
    streams:
      application-id: device-status-streams
      properties:
        auto.offset.reset: latest

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.qtech.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mybatis/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml
  configuration:
    jdbc-type-for-null: null
    call-setters-on-nulls: true
    useGeneratedKeys: false

mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: com.qtech.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mybatis/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml
  configuration:
    jdbc-type-for-null: null
    call-setters-on-nulls: true
    useGeneratedKeys: false
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false

# PageHelper分页插件
pagehelper:
  # 多数据源自动识别，分页时自动调整分页语句
  autoRuntimeDialect: true
#  helperDialect: oracle
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# 代码生成
gen:
  # 作者
  author: qtech
  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool
  packageName: com.qtech.im.bb
  # 自动去除表前缀，默认是true
  autoRemovePre: false
  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）
  tablePrefix: sys_


tbs:
  deptName: COB
  deptNames:
    - COB
    - COB车间
#    - 车载
  deviceTypes:
    - DB
    - WB
    - HM
    - AA
  sortFactoryNameCaseStatement: "(case company_name when '台虹厂区' then 1 when '古城厂区' then 2 when '汉浦厂区' then 3 when 'QT_India' then 4 else 5 end)"
  sortGroupNameCaseStatement: "(case when group_name like '%COB一%' then 1 when group_name like '%COB二%' then 2 when group_name like '%COB三%' then 3 when group_name like '%COB四%' then 4 when group_name like '%COB五%' then 5 when group_name like '%COB六%' then 6 when group_name like '%COB七%' then 7 when group_name like '%COB八%' then 8 when group_name like '%COB九%' then 9 when group_name like '%COB十%' then 10 when group_name like '%试产一%' then 11 when group_name like '%试产二%' then 12 when group_name like '%试产三%' then 13 when group_name like '%一%' then 14 when group_name like '%二%' then 15 when group_name like '%三%' then 16 when group_name like '%修复%' then 17 else 20 end)"
  sortDeviceTypeCaseStatement: "(case device_type when 'DB' then 1 when 'WB' then 2 when 'HM' then 3 when 'AA' then 4 else 5 end)"