# 项目相关配置
ruoyi:
  # 名称
  name: RuoYi
  # 版本
  version: 3.8.8
  # 版权年份
  copyrightYear: 2024
  # 文件路径 示例（ Windows配置D:/qtech/uploadPath，Linux配置 /home/qtech/uploadPath）
  profile: /home/qtech/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8079
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.qtech: debug
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: prod
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
#  redis:
#    ## Redis数据库索引（默认为0）
#    database: 0
#    ## Redis服务器连接密码（默认为空）
#    password: im@2024
#    ## 连接超时时间（毫秒）
#    timeout: 5000
#    ## 集群配置
#    cluster:
#      ### 集群中所有节点
#      nodes:
#        - 10.170.6.24:6379
#        - 10.170.6.25:6379
#        - 10.170.6.26:6379
#        - 10.170.6.141:6379
#        - 10.170.6.142:6379
#        - 10.170.1.68:6379
#      ### 最大重定向数，最好为集群节点数，比如第一台挂了，连第二台，第二台挂了连第三台，这个是重新连接的最大数量
#      max-redirects: 3
#    lettuce:
#      read-from: REPLICA_PREFERRED # 配置从节点优先读
#      pool:
#        ## 连接池最大连接数（使用负值表示没有限制）
#        max-active: 20
#        ## 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: -1
#        ## 连接池中的最大空闲连接
#        max-idle: 10
#        ## 连接池中的最小空闲连接
#        min-idle: 5
#      ## 集群配置
#      cluster:
#        refresh:
#          # 支持集群拓扑动态感应刷新,自适应拓扑刷新是否使用所有可用的更新，默认false关闭，类似nacos定时刷新服务列表
#          adaptive: true
#          # 定时刷新时间 毫秒
#          period: 2000

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.qtech.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mybatis/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml
  configuration:
    jdbc-type-for-null: null
    call-setters-on-nulls: true
    useGeneratedKeys: false

mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: com.qtech.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mybatis/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml
  configuration:
    jdbc-type-for-null: null
    call-setters-on-nulls: true
    useGeneratedKeys: false
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# PageHelper分页插件
pagehelper:
  # 多数据源自动识别，分页时自动调整分页语句
  autoRuntimeDialect: true
  helperDialect: oracle
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# 代码生成
gen:
  # 作者
  author: qtech
  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool
  packageName: com.qtech.im.bb
  # 自动去除表前缀，默认是true
  autoRemovePre: false
  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）
  tablePrefix: sys_

fixture:
  statistics:
    url: http://127.0.0.1:5000/fixture/statistics/line